### PR TITLE
Added color handling and fixed double newline.

### LINKED ISSUE #3: Colored output
I think might be awesome to add colored output for development for each process, a la docker-compose.
https://github.com/mcollina/color-prefix-stream/blob/master/index.js has the relevant logic.

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #3.

I also fixed a double newline problem.

You might think of using a `StringDecoder`, as you might have a problem with utf8 output, if you want I can send another PR.

### CODE REVIEW

**Comment by mafintosh** [comment]
AWESOME

**Comment by mafintosh** [comment]
pr for the utf-8 stuff is appreciated if it is easy to fix :)

**Comment by mafintosh** [comment]
2.5.0

**Comment by mcollina** [comment]
To solve the utf-8 problem, we should use split2 and color-prefix-stream, is a bit of a change, should I do a PR?

**Pull request merged**
